version: '3.4'
services:
  grafana:
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    image: grafana/grafana
    restart: unless-stopped
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - influxdb2

  influxdb2:
    container_name: influxdb2
    image: influxdb:2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - influxdb2:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    command: [ "--config-directory=/etc/telegraf/telegraf.d"]
    restart: always
    volumes:
      - ${PWD}/telegraf:/etc/telegraf:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      # Add user telegraf to host and docker group first
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      HOST_PROC: "/host/proc"
      INFLUXDB_URL: $INFLUXDB_URL
      INFLUXDB_TOKEN: $INFLUXDB_TOKEN
      HOSTNAME: $HOSTNAME
    depends_on:
      - influxdb2

volumes:
  influxdbdata:
    external: true
  influxdb2:
  influxdb2-config:
 
